### ISSUE TITLE
你好，作者，预训练模型下载？

### ISSUE THREAD

**Issue by Wisdom2wisdom** [DevilExileSu/transformer#2]
你好，预训练模型下载位置？

**Comment by DevilExileSu** [comment]
你指的是使用到的spaCy预训练模型吗？在[spaCy](https://github.com/explosion/spaCy)的GitHub主页上有说明，或者是在https://spacy.io/usage/models这里查看。
```
# Download best-matching version of specific model for your spaCy installation
python -m spacy download en_core_web_sm

# pip install .tar.gz archive or .whl from path or URL
pip install /Users/you/en_core_web_sm-3.0.0.tar.gz
pip install /Users/you/en_core_web_sm-3.0.0-py3-none-any.whl
pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
```
下载安装完成后，只需要在代码中导入即可，不需要指定位置
```python
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("This is a sentence.")
```
spaCy只是用来进行分词，生成训练用到的字典集，实际模型中没有使用到spaCy，如果不是为了自己制作数据集的话用不到的。

如果你指的是这个项目Transformer训练好的模型，我好像没有保留...

**Comment by DevilExileSu** [comment]
> 你指的是使用到的spaCy预训练模型吗？在[spaCy](https://github.com/explosion/spaCy)的GitHub主页上有说明，或者是在[https://spacy.io/usage/models]这里查看。(https://spacy.io/usage/models%E8%BF%99%E9%87%8C%E6%9F%A5%E7%9C%8B%E3%80%82)
> 
> ```
> # Download best-matching version of specific model for your spaCy installation
> python -m spacy download en_core_web_sm
> 
> # pip install .tar.gz archive or .whl from path or URL
> pip install /Users/you/en_core_web_sm-3.0.0.tar.gz
> pip install /Users/you/en_core_web_sm-3.0.0-py3-none-any.whl
> pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
> ```
> 
> 下载安装完成后，只需要在代码中导入即可，不需要指定位置
> 
> ```python
> import spacy
> nlp = spacy.load("en_core_web_sm")
> doc = nlp("This is a sentence.")
> ```
> 
> spaCy只是用来进行分词，生成训练用到的字典集，实际模型中没有使用到spaCy，如果不是为了自己制作数据集的话用不到的。
> 
> 如果你指的是这个项目 Transformer (变压器) 训练好的模型，我好像没有保留...

**Comment by DevilExileSu** [comment]
> > 你指的是使用到的spaCy预训练模型吗？在[spaCy](https://github.com/explosion/spaCy)的GitHub主页上有说明，或者是在https://spacy.io/usage/models 这里查看。
> > ```
> > # Download best-matching version of specific model for your spaCy installation
> > python -m spacy download en_core_web_sm
> > 
> > # pip install .tar.gz archive or .whl from path or URL
> > pip install /Users/you/en_core_web_sm-3.0.0.tar.gz
> > pip install /Users/you/en_core_web_sm-3.0.0-py3-none-any.whl
> > pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 下载安装完成后，只需要在代码中导入即可，不需要指定位置
> > ```python
> > import spacy
> > nlp = spacy.load("en_core_web_sm")
> > doc = nlp("This is a sentence.")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > spaCy只是用来进行分词，生成训练用到的字典集，实际模型中没有使用到spaCy，如果不是为了自己制作数据集的话用不到的。
> > 如果你指的是这个项目 Transformer (变压器) 训练好的模型，我好像没有保留...

**Comment by Wisdom2wisdom** [comment]
你好 ，作者，百忙之中感谢你的回答，但是目前我预训练模型下载失败？

(All) E:\program_code\machine_Translation\transformer-main>python -m spacy download en_core_web_sm
2022-07-28 00:08:16.800623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001949FB316C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by Wisdom2wisdom** [comment]
> 你好 ，作者，百忙之中感谢你的回答，但是目前我预训练模型下载失败？
> 
> (All) E:\program_code\machine_Translation\transformer-main>python -m spacy download en_core_web_sm 2022-07-28 00:08:16.800623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll Traceback (most recent call last): File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connection.py", line 175, in _new_conn (self._dns_host, self.port), self.timeout, **extra_kw File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\socket.py", line 752, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno 11004] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connectionpool.py", line 710, in urlopen chunked=chunked, File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn conn.connect() File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connection.py", line 358, in connect self.sock = conn = self._new_conn() File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connection.py", line 187, in _new_conn self, "Failed to establish a new connection: %s" % e urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001949FB316C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\requests\adapters.py", line 449, in send timeout=timeout File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\connectionpool.py", line 786, in urlopen method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2] File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\urllib3\util\retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001949FB316C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\spacy__main__.py", line 4, in setup_cli() File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\spacy\cli_util.py", line 71, in setup_cli command(prog_name=COMMAND) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\click\core.py", line 1128, in **call** return self.main(*args, **kwargs) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\click\core.py", line 1053, in main rv = self.invoke(ctx) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\click\core.py", line 1659, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\click\core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\click\core.py", line 754, in invoke return __callback(*args, **kwargs) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\typer\main.py", line 532, in wrapper return callback(**use_params) # type: ignore File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\spacy\cli\download.py", line 35, in download_cli download(model, direct, sdist, *ctx.args) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\spacy\cli\download.py", line 67, in download compatibility = get_compatibility() File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\spacy\cli\download.py", line 78, in get_compatibility r = requests.get(about.**compatibility**) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\requests\api.py", line 76, in get return request('get', url, params=params, **kwargs) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\requests\api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\requests\sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\requests\sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "C:\D_installation_packet\Anaconda\installion_package\envs\All\lib\site-packages\requests\adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /explosion/spacy-models/master/compatibility.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001949FB316C8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

这是通过：python -m spacy download en_core_web_sm进行下载

**Comment by Wisdom2wisdom** [comment]
> 你好 ，作者，百忙之中感谢你的回答，但是目前我预训练模型下载失败？
> 
这是通过：python -m spacy download en_core_web_sm进行下载

**Comment by Wisdom2wisdom** [comment]
你好，作者，繁忙之中谢谢你的解答，我现在进行下载python -m spacy download en_core_web_sm失败？请问有什么方法解决吗？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DevilExileSu/transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DevilExileSu/transformer] 你好，作者，预训练模型下载？ (Issue #2)





   
你指的是使用到的spaCy预训练模型吗？在spaCy的GitHub主页上有说明，或者是在https://spacy.io/usage/models 这里查看。
 # Download best-matching version of specific model for your spaCy installation python -m spacy download en_core_web_sm # pip install .tar.gz archive or .whl from path or URL pip install /Users/you/en_core_web_sm-3.0.0.tar.gz pip install /Users/you/en_core_web_sm-3.0.0-py3-none-any.whl pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz  
下载安装完成后，只需要在代码中导入即可，不需要指定位置
 import spacy nlp = spacy.load("en_core_web_sm") doc = nlp("This is a sentence.")
 
spaCy只是用来进行分词，生成训练用到的字典集，实际模型中没有使用到spaCy，如果不是为了自己制作数据集的话用不到的。
 如果你指的是这个项目 Transformer (变压器) 训练好的模型，我好像没有保留...

**Comment by DevilExileSu** [comment]
你可以到 https://spacy.io/usage/models 找到对应的预训练模型下载到本地，然后在预训练模型所在目录下用`pip install en_core_web_sm`来安装
```shell
# pip install .tar.gz archive or .whl from path or URL
pip install /Users/you/en_core_web_sm-3.0.0.tar.gz
pip install /Users/you/en_core_web_sm-3.0.0-py3-none-any.whl
```
> 链接：https://pan.baidu.com/s/1IkkRegM9rF4arzWAv4venQ 
> 提取码：vz0e
这是用到的预训练模型

**Comment by Wisdom2wisdom** [comment]
> 你可以到 https://spacy.io/usage/models 找到对应的预训练模型下载到本地，然后在预训练模型所在目录下用`pip install en_core_web_sm`来安装
> 
> ```shell
> # pip install .tar.gz archive or .whl from path or URL
> pip install /Users/you/en_core_web_sm-3.0.0.tar.gz
> pip install /Users/you/en_core_web_sm-3.0.0-py3-none-any.whl
> ```
> 
> > 链接：https://pan.baidu.com/s/1IkkRegM9rF4arzWAv4venQ
> > 提取码：vz0e
> > 这是用到的预训练模型

你好，感谢你的帮助，预训练模型已经解决，现在train.py遇到了关键问题？
C:\D_installation_packet\Anaconda\installion_package\envs\All\python.exe E:/program_code/machine_Translation/transformer-main/train.py
2022-07-29 18:23:10.968971: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "E:/program_code/machine_Translation/transformer-main/train.py", line 63, in <module>
    cfg.print_config()
  File "E:\program_code\machine_Translation\transformer-main\config\cfg.py", line 25, in print_config
    for k,v in self.config.items():
AttributeError: 'NoneType' object has no attribute 'items'

Process finished with exit code 1

**Comment by Wisdom2wisdom** [comment]
你好，感谢你的帮助，预训练模型已经解决，现在train.py遇到了关键问题？


C:\D_installation_packet\Anaconda\installion_package\envs\All\python.exe E:/program_code/machine_Translation/transformer-main/train.py
2022-07-29 18:23:10.968971: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
&nbsp; File "E:/program_code/machine_Translation/transformer-main/train.py", line 63, in <module&gt;
&nbsp; &nbsp; cfg.print_config()
&nbsp; File "E:\program_code\machine_Translation\transformer-main\config\cfg.py", line 25, in print_config
&nbsp; &nbsp; for k,v in self.config.items():
AttributeError: 'NoneType' object has no attribute 'items'


Process finished with exit code 1

**Comment by DevilExileSu** [comment]
😂感谢提醒，之前把 [模板](https://github.com/DevilExileSu/pytorch-template) 和那几个示例代码搞混了，有些代码更新了有些没有，也忘了去修改，重新拉一下代码，或者直接修改`config/cfg.py`里的`__init__`就可以了

```python
class Config(object):
    def __init__(self, logger, args):
        self.logger = logger
        self.config = vars(args)
```

**Comment by Wisdom2wisdom** [comment]
> 😂感谢提醒，之前把 [模板](https://github.com/DevilExileSu/pytorch-template) 和那几个示例代码搞混了，有些代码更新了有些没有，也忘了去修改，重新拉一下代码，或者直接修改`config/cfg.py`里的`__init__`就可以了
> 
> ```python
> class Config(object):
>     def __init__(self, logger, args):
>         self.logger = logger
>         self.config = vars(args)
> ```

谢谢作者，在你的指示下已经完成了训练，现在test.py遇到了如下问题？麻烦你再解答一下



C:\D_installation_packet\Anaconda\installion_package\envs\yolox\python.exe E:/program_code/machine_Translation/transformer-main—官方/transformer-main/test.py --sent 这是一个例子
Traceback (most recent call last):
  File "E:/program_code/machine_Translation/transformer-main—官方/transformer-main/test.py", line 48, in <module>
    cfg = Config(logger)
TypeError: __init__() missing 1 required positional argument: 'args'

Process finished with exit code 1

**Comment by Wisdom2wisdom** [comment]
谢谢作者，在你的指示下已经完成了训练，现在test.py遇到了如下问题？麻烦你再解答一下




C:\D_installation_packet\Anaconda\installion_package\envs\yolox\python.exe E:/program_code/machine_Translation/transformer-main—官方/transformer-main/test.py --sent 这是一个例子
Traceback (most recent call last):
File "E:/program_code/machine_Translation/transformer-main—官方/transformer-main/test.py", line 48, in
cfg = Config(logger)
TypeError:&nbsp;init() missing 1 required positional argument: 'args'

Process finished with exit code 1





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DevilExileSu/transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月30日(星期六) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DevilExileSu/transformer] 你好，作者，预训练模型下载？ (Issue #2)





 
😂感谢提醒，之前把 模板 和那几个示例代码搞混了，有些代码更新了有些没有，也忘了去修改，重新拉一下代码，或者直接修改config/cfg.py里的__init__就可以了
 class Config(object):     def __init__(self, logger, args):         self.logger = logger         self.config = vars(args)

**Comment by DevilExileSu** [comment]
把`args`传进去就好了，之前`args`默认为`None`，现在去掉了，必须传进去一个`args`
```python 
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--sent', type=str, required=True)
    args = parser.parse_args()

    src_vocab = Vocab()
    trg_vocab = Vocab()
    
    logger = Logger()
    cfg = Config(logger, args)
    ......
```

**Comment by Wisdom2wisdom** [comment]
> 把`args`传进去就好了，之前`args`默认为`None`，现在去掉了，必须传进去一个`args`
> 
> ```python
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--sent', type=str, required=True)
>     args = parser.parse_args()
> 
>     src_vocab = Vocab()
>     trg_vocab = Vocab()
>     
>     logger = Logger()
>     cfg = Config(logger, args)
>     ......
> ```
你好，作者，非常感谢你的帮助，下面2个问题希望可以获取你的帮助。

问题①：下图中输入：这是一个例子，我希望输出：this is a example。 希望获取作者帮忙解决，谢谢你

python test.py --sent 这是一个例子
"""
2021-03-14 12:09:39,281 [DEBUG]: Config loaded from file config.json
这是一个例子
['<sos>', '这是', '一个', '例子', '<eos>']
['<sos>', 'this', 'is', 'a', 'example', '<eos>']
"""


问题②：运行出来进行test.py测试，发现输出全部不对，请问我这是你出问题了吗？谢谢

C:\D_installation_packet\Anaconda\installion_package\envs\yolox\python.exe E:/program_code/machine_Translation/transformer-main—官方/transformer-main/test.py --sent 这是一个例子
2022-07-31 18:01:17,380 [DEBUG]: Config loaded from file config.json
这是一个例子
['<sos>', '这是', '一个', '例子', '<eos>']
['<sos>', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the']

Process finished with exit code 0

**Comment by DevilExileSu** [comment]
模型没有收敛，试着调整一下参数

**Comment by Wisdom2wisdom** [comment]
首先谢谢帮助，我发现训练时候loss值保持在6~8之间，我在网上看了，想将数据集预处理降低loss损失，可是并没有合适的方法，请问这有什么合适办法吗？谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DevilExileSu/transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DevilExileSu/transformer] 你好，作者，预训练模型下载？ (Issue #2)





 
模型没有收敛，试着调整一下参数

**Comment by Wisdom2wisdom** [comment]
你好，在打扰你一下，请问我计划用自己数据集制作train.zh，以及train.zh.token，该如何制作啊，谢谢啊

**Comment by DevilExileSu** [comment]
如何制作可以参考utils/vocab.py中代码，train.zh和train.en是未进行处理的原始句子，zh和en每行对应，main函数是一个示例。调用Vocab.create()方法时，会对原始句子进行分词，并将结果写入train.zh.token， train.en.token文件中， 包含有统计信息、映射表的字典类也会被序列化到本地。

**Comment by Wisdom2wisdom** [comment]
你好，作者，非常感谢你的帮助，下面2个问题希望可以获取你的帮助。


问题①：下图中输入：这是一个例子，我希望输出：this is a example。 希望获取作者帮忙解决，谢谢你




问题②：运行出来进行test.py测试，发现输出全部不对，请问我这是你出问题了吗？谢谢
C:\D_installation_packet\Anaconda\installion_package\envs\yolox\python.exe E:/program_code/machine_Translation/transformer-main—官方/transformer-main/test.py --sent 这是一个例子
2022-07-31 18:01:17,380 [DEBUG]: Config loaded from file config.json
这是一个例子
['<sos&gt;', '这是', '一个', '例子', '<eos&gt;']
['<sos&gt;', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the', 'the']


Process finished with exit code 0
